// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAKRILDfKNXjbcTOowNLPM7IzF2lFlz4w',
    appId: '1:385228720463:android:7c042c1cc8fab042b81d3a',
    messagingSenderId: '385228720463',
    projectId: 'run-app-db2eb',
    storageBucket: 'run-app-db2eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E-yPX8SkZXGqzjsH45vAkYqtM3scm-4',
    appId: '1:385228720463:ios:dd201fcba281510cb81d3a',
    messagingSenderId: '385228720463',
    projectId: 'run-app-db2eb',
    storageBucket: 'run-app-db2eb.firebasestorage.app',
    androidClientId: '385228720463-000buv634vdef58rfqr2c7h8q1ekkic4.apps.googleusercontent.com',
    iosClientId: '385228720463-7cmmsj2htkm1g0u07ld9vkjgbe2ophdv.apps.googleusercontent.com',
    iosBundleId: 'com.magdata.runApp',
  );

}